import os
import sys
import json
from datetime import datetime
from dotenv import load_dotenv

load_dotenv()

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from Indian_stock_analyzer.stock_analysis_crew import create_stock_analysis_crew
from Indian_stock_analyzer.config import Config


class ReportGenerator:
    """Generate professional investment memorandum reports"""
    
    def __init__(self, output_dir: str = None):
        self.output_dir = output_dir or Config.OUTPUT_DIR
        os.makedirs(self.output_dir, exist_ok=True)
    
    def _parse_llm_result(self, result_text: str) -> dict:
        """Parse the LLM output into structured data"""
        lines = result_text.strip().split('\n')
        data = {
            'rating': 'HOLD',
            'target_price': None,
            'stop_loss': None,
            'time_horizon': 'Medium-term',
            'rationale': result_text,
            'risk_level': 'Medium',
            'key_factors': []
        }
        
        result_lower = result_text.lower()
        
        if 'strong buy' in result_lower:
            data['rating'] = 'STRONG BUY'
        elif ' buy ' in result_lower and 'strong' not in result_lower:
            data['rating'] = 'BUY'
        elif 'strong sell' in result_lower:
            data['rating'] = 'STRONG SELL'
        elif ' sell ' in result_lower and 'strong' not in result_lower:
            data['rating'] = 'SELL'
        
        if 'short-term' in result_lower or 'short term' in result_lower:
            data['time_horizon'] = 'Short-term'
        elif 'long-term' in result_lower or 'long term' in result_lower:
            data['time_horizon'] = 'Long-term'
        
        if 'low risk' in result_lower or 'conservative' in result_lower:
            data['risk_level'] = 'Low'
        elif 'high risk' in result_lower or 'aggressive' in result_lower:
            data['risk_level'] = 'High'
        
        return data
    
    def generate_memorandum(self, symbol: str, analysis_result: dict) -> str:
        """Generate professional investment memorandum"""
        
        parsed = self._parse_llm_result(analysis_result.get('result', ''))
        
        timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        
        memo = f"""
{'='*70}
                    INVESTMENT MEMORANDUM
                    Indian Equity Stock Analysis
{'='*70}

Stock: {symbol.upper()}
Analysis Date: {timestamp}
Generated by: AI Multi-Agent Stock Analysis System

{'='*70}
                          RECOMMENDATION
{'='*70}

INVESTMENT RATING:     {parsed['rating']}
TIME HORIZON:          {parsed['time_horizon']}
RISK LEVEL:            {parsed['risk_level']}

{'='*70}
                        RATIONALE
{'='*70}

{parsed['rationale'][:2000]}

{'='*70}
                      RISK PARAMETERS
{'='*70}

- Market Risk: Overall market volatility and sector-specific risks
- Liquidity Risk: Trading volume and bid-ask spread considerations  
- Company Risk: Fundamental risks specific to the business
- Macroeconomic Risk: RBI policy, inflation, currency fluctuations
- Regulatory Risk: Changes in SEBI regulations or sector policies

{'='*70}
                    DISCLAIMER
{'='*70}

This analysis is generated by an AI system and should not be considered 
as professional financial advice. Investors should conduct their 
own due diligence and consult with qualified financial advisors 
before making investment decisions.

The stock market investments involve risks, including the 
potential loss of capital. Past performance does not 
guarantee future results.

{'='*70}
"""
        
        return memo
    
    def save_report(self, symbol: str, analysis_result: dict, format: str = 'text') -> str:
        """Save analysis report to file"""
        
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        
        if format == 'json':
            filename = f"{self.output_dir}/analysis_{symbol}_{timestamp}.json"
            with open(filename, 'w') as f:
                json.dump(analysis_result, f, indent=2, default=str)
        else:
            memo = self.generate_memorandum(symbol, analysis_result)
            filename = f"{self.output_dir}/memo_{symbol}_{timestamp}.txt"
            with open(filename, 'w') as f:
                f.write(memo)
        
        return filename


def analyze_stock(stock_symbol: str, company_name: str = None) -> dict:
    """Analyze an Indian stock using the multi-agent CrewAI system"""
    
    print(f"\n{'='*60}")
    print(f"INDIAN STOCK ANALYSIS SYSTEM")
    print(f"{'='*60}")
    print(f"Analyzing: {stock_symbol.upper()} ({company_name or 'Auto-detect'})")
    print(f"Started at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print(f"{'='*60}\n")
    
    try:
        crew_system = create_stock_analysis_crew(stock_symbol)
        result = crew_system.run_analysis()
        
        report_gen = ReportGenerator()
        report_path = report_gen.save_report(stock_symbol, result)
        
        print(f"\n{'='*60}")
        print("ANALYSIS COMPLETE")
        print(f"{'='*60}")
        print(f"Report saved to: {report_path}")
        
        memo = report_gen.generate_memorandum(stock_symbol, result)
        print(memo)
        
        return result
        
    except Exception as e:
        print(f"\nError during analysis: {str(e)}")
        import traceback
        traceback.print_exc()
        return {
            "symbol": stock_symbol.upper(),
            "error": str(e),
            "analysis_date": datetime.now().isoformat()
        }


def list_available_tickers():
    """List default Indian stock tickers for analysis"""
    return Config.DEFAULT_TICKERS


def run_demo():
    """Run demo analysis on default stocks"""
    
    default_stocks = [
        ("RELIANCE", "Reliance Industries Ltd"),
        ("TCS", "Tata Consultancy Services Ltd"),
        ("INFY", "Infosys Ltd"),
    ]
    
    results = []
    
    for symbol, name in default_stocks:
        print(f"\n{'#'*60}")
        print(f"### Analyzing: {symbol} - {name}")
        print(f"{'#'*60}")
        
        result = analyze_stock(symbol, name)
        results.append(result)
        
        print(f"\nCompleted: {symbol}")
    
    return results


def main():
    """Main entry point"""
    
    import argparse
    
    parser = argparse.ArgumentParser(description='Indian Stock Analysis Multi-Agent System')
    parser.add_argument('stock', nargs='?', help='Stock symbol (e.g., RELIANCE, TCS, INFY)')
    parser.add_argument('--name', help='Company name')
    parser.add_argument('--demo', action='store_true', help='Run demo on default stocks')
    parser.add_argument('--list', action='store_true', help='List available stock tickers')
    
    args = parser.parse_args()
    
    if args.list:
        print("Available Indian Stock Tickers:")
        for ticker in list_available_tickers():
            print(f"  - {ticker}")
        return
    
    if args.demo:
        run_demo()
        return
    
    if args.stock:
        result = analyze_stock(args.stock, args.name)
    else:
        parser.print_help()
        print("\nExample usage:")
        print("  python -m stock_analysis.main RELIANCE")
        print("  python -m stock_analysis.main TCS --name 'Tata Consultancy Services'")
        print("  python -m stock_analysis.main --demo")
        print("  python -m stock_analysis.main --list")


if __name__ == "__main__":
    main()